services:
  node:
    image: "node:22"
    user: "node"
    working_dir: /home/node/app
    expose:
      - 3000
    networks:
      - dokploy-network
    volumes:
      - ./:/home/node/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.<unique-name>.rule=Host(`snekpvp.lol`)"
      - "traefik.http.routers.<unique-name>.entrypoints=websecure"
      - "traefik.http.routers.<unique-name>.tls.certResolver=letsencrypt"
      - "traefik.http.services.<unique-name>.loadbalancer.server.port=3000"
    command: "make start-dev"
networks:
  dokploy-network:
    external: true