services:
  node:
    build:
      context: .
      dockerfile: node.Dockerfile
    user: "node"
    working_dir: /home/node/app
    expose:
      - ${PORT}
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.node.entrypoints=websecure"
      - "traefik.http.routers.node.tls.certResolver=letsencrypt"
      - "traefik.http.services.node.loadbalancer.server.port=${PORT}"
networks:
  dokploy-network:
    external: true