services:
  node:
    build:
      context: .
      dockerfile: node.Dockerfile
    user: "node"
    working_dir: /home/node/app
    expose:
      - 3000
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node.rule=Host(`snekpvp.lol`)"
      - "traefik.http.routers.node.entrypoints=websecure"
      - "traefik.http.routers.node.tls.certResolver=letsencrypt"
      - "traefik.http.services.node.loadbalancer.server.port=3000"
networks:
  dokploy-network:
    external: true